services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: store_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  sta-api:
    container_name: sta-api
    image: sta/sta:1.0.1
    ports:
      - 8090:8090
    networks:
      - spring-demo
    depends_on:
      - postgres
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
